# Generated by Django 5.1.2 on 2024-11-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_description_task_showdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='showDescription',
        ),
    ]
